config/routes.rb
Rails.application.routes.draw do
  resources :meals

  resources :balls

  resources :kittens

  root 'kittens#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
  belongs_to :kitten
end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  has_many :balls, dependent: :destroy
  has_many :meals, dependent: :destroy

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  after_commit :medal



  belongs_to :kitten

  def medal
    self.kitten.balls.create!(color: 'за кормежку') if self.done
  end








end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController
  before_action :set_ball, only: [:show, :edit, :update, :destroy]

  # GET /balls
  # GET /balls.json
  def index
    @balls = Ball.all
  end

  # GET /balls/1
  # GET /balls/1.json
  def show
  end

  # GET /balls/new
  def new
    @ball = Ball.new
  end

  # GET /balls/1/edit
  def edit
  end

  # POST /balls
  # POST /balls.json
  def create
    @ball = Ball.new(ball_params)

    respond_to do |format|
      if @ball.save
        format.html { redirect_to @ball, notice: 'Ball was successfully created.' }
        format.json { render :show, status: :created, location: @ball }
      else
        format.html { render :new }
        format.json { render json: @ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /balls/1
  # PATCH/PUT /balls/1.json
  def update
    respond_to do |format|
      if @ball.update(ball_params)
        format.html { redirect_to @ball, notice: 'Ball was successfully updated.' }
        format.json { render :show, status: :ok, location: @ball }
      else
        format.html { render :edit }
        format.json { render json: @ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /balls/1
  # DELETE /balls/1.json
  def destroy
    @ball.destroy
    respond_to do |format|
      format.html { redirect_to balls_url, notice: 'Ball was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ball
      @ball = Ball.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ball_params
      params.require(:ball).permit(:color, :kitten_id)
    end
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  # GET /kittens
  # GET /kittens.json
  def index
    @kittens = Kitten.all
  end

  # GET /kittens/1
  # GET /kittens/1.json
  def show
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
  end

  # POST /kittens
  # POST /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: 'Kitten was successfully created.' }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1
  # PATCH/PUT /kittens/1.json
  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten, notice: 'Kitten was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kittens/1
  # DELETE /kittens/1.json
  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: 'Kitten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :male, :weight)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:kitten_id, :done, :kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/balls/_form.html.erb
<%= form_for(@ball) do |f| %>
  <% if @ball.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ball.errors.count, "error") %> prohibited this ball from being saved:</h2>

      <ul>
      <% @ball.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">

    <%= f.select :kitten_id, Kitten.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balls/edit.html.erb
<h1>Editing ball</h1>

<%= render 'form' %>

<%= link_to 'Show', @ball %> |
<%= link_to 'Back', balls_path %>

app/views/balls/index.html.erb
<h1>Listing balls</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @balls.each do |ball| %>
      <tr>
        <td><%= ball.color %></td>
        <td><%= ball.kitten.try(:name) %></td>
        <td><%= link_to 'Show', ball %></td>
        <td><%= link_to 'Edit', edit_ball_path(ball) %></td>
        <td><%= link_to 'Destroy', ball, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ball', new_ball_path %>

app/views/balls/new.html.erb
<h1>New ball</h1>

<%= render 'form' %>

<%= link_to 'Back', balls_path %>

app/views/balls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @ball.color %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @ball.kitten.try(:name) %>
</p>

<%= link_to 'Edit', edit_ball_path(@ball) %> |
<%= link_to 'Back', balls_path %>

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
      <% @kitten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :male %><br>
    <%= f.check_box :male %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render 'form' %>

<%= link_to 'Show', @kitten %> |
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Listing kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Male</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.male %></td>
        <td><%= kitten.weight %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>

<p>
  <strong>Male:</strong>
  <%= @kitten.male %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @kitten.weight %>
</p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cat</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Коты', kittens_path %>
<%= link_to 'Шары', balls_path %>
<%= link_to 'Кормление', meals_path %>


<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kitten_id %><br>
    <%= f.select :kitten_id, Kitten.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <thead>
    <tr>
      <th>Kitten</th>
      <th>Done</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.kitten_id %></td>
        <td><%= meal.done %></td>
        <td><%= meal.kind %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kitten:</strong>
  <%= @meal.kitten_id %>
</p>

<p>
  <strong>Done:</strong>
  <%= @meal.done %>
</p>

<p>
  <strong>Type:</strong>
  <%= @meal.kind %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>